//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMtoKOPS.Output {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMtoKOPS.Output.HtmlResources", typeof(HtmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Browse_3 {
            get {
                object obj = ResourceManager.GetObject("Browse_3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhDQALAIAAAAAAAP///yH5BAEAAAEALAAAAAANAAsAAAIajA15i6ncHDwSPtCoxA6HDl7bV5FIZj0peBQAOw==.
        /// </summary>
        public static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhDQALAOMAAAAAAL8AAAC/AL+/AAAAv78AvwC/v8DAwICAgP8AAP///////////////////////yH5BAEAAA8ALAAAAAANAAsAAAQa8MmZprUpX5z17uAFjtRISmYnmttztmpLbREAOw==.
        /// </summary>
        public static string d {
            get {
                return ResourceManager.GetString("d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAANoAyR7JDqIOk+UT2mkaXWqdX6wfo65jpvCm6fIp7LOsrjSuMvcy9bm1v39
        ////QAAACH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827/2AojiRjDGiqrqhRvswAzHRtzwNcyndP
        ///57oRz9cDBkNDgGBJWwpqxuNnGHBYEYCqNfCTImlaqyDMxXlBVKuVQe6ePWm1o6AuA6JvTdzRkDvs
        ///eHkYewN+gIIcewEJcoeIemB1YX9uj4ORWwB0mWaWl0RFnp+gNoGiMaQ3pkcKCQmjqZ0Wra8hCwUB
        ///dgEDBgsUCAbBwsPEwQgUt7lgvL4bCwZ2NwHHMM/RNtMaC0+pBS/bsd6wpKsdSeQXBrE1tSHq6zPt
        ///EglNTEpjWU6yH/Q3TvpQKhSgoeaJFQUADKyhIa/DQGx+KLGjwA0AAysEBFhpAICRg3f+d0JUxNSo
        ///1IQFdjYdIKAGQB+JSkCglK [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d1 {
            get {
                return ResourceManager.GetString("d1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAMEGBsRDPsdTTsVkXNR1cseHfciVicmmmcm0puSVleuwsMrGt8vcy/PQ0P79
        ////QAAACH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827XAjijSRXAGgqFEvpkkaQzunx3tki0zxQ
        ///4ECKoEccBIEnIlF0dCFogWgqukMJmi4CzcFNoLgOGhPrqX7BMjDtSu4seGBHA6CeBdqd5zZOqE/x
        ///HHozYA1xYTSAG297DgOGPIkbcFwACnFrkRpmdJScnSk/mRgGjCh9nyhjohabSiqrGQeuPAEtsBgD
        ///szOqgCC8FaS6BpFJMyu2FQitKQPIbTGuNhcIBFRRzRUFAtvc3d7boRU6uj44Q+SvFufkRi/r6GwU
        ///xei/He/k8RKCVChS/f75RtwDYM1fuglazjhI40ABgFNzUrkYaOjQQQlVCjUKwGWOJQf+CQEEtDfp
        ///kjEKi0x1cURJY5U7JShyEW [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d10 {
            get {
                return ResourceManager.GetString("d10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAAFmARp2GiR7JDqIOkSORE2STVmaWWmkaXWqdX6wfo65jpvCm67Mrsvcy9bm
        ///1v39/SH5BAEAAA0ALAAAAAA/AD8AAAT+sMlJq7046827ZKAnjhwiBAEABEXCkPCYCGptC0usZ8yQ
        ///2sAVYkekFIJIlaFITCSTgRcTxvipCNgflmArTGGI22O8AAjGD1ot9xUNxOjBeaxWedseqxn9aMzT
        ///NgN4HQxAf2MIaHVmgxyFcA8OfIA1AY0bjzV/BpOLlpcaen84fIt3oBiLowGlNgmoGQqQNIl0NlKw
        ///F29PSKe5Fgt6vGa4vxYGw5VsoCDFFgnCQQEKGs0xJigqLC4XDIs2AQfOE9g/2+MXM084GAsIBAPx
        ///AwboDepJ7Dw+wwFDOz3RgPTLcCSZkh0FDS55ZrBSvQ1OGq5wVmXFFhUDCNAIgGWXLw/+FYFsudil
        ///QpgVcQCMKZRgTIM1JE5CUg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d11 {
            get {
                return ResourceManager.GetString("d11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAANnAzqIOl6dXsEHB8RDPsxiXseGe4u4i5W9lazLrM6pnsrGt8vcy9jo2PPQ
        ///0P39/SH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827XMrijSRnDGhKGGLpjmcqp8prZwsx76hx
        ////5QCb1gA/mJDXstYWswIUFVUxXQhUY+sApud1aojnSyb1ZGfYI9zRn44BmcZId3ZstuGOJW+sY+z
        ///Dm0PO3wba38PBYKEhRo7ZwptaI0ZYilxkjI+lBh+XIMDeV0yS5wWlkmTpheeqSgEpasVQq40shpX
        ///SZsYCb2rCqgzBbETBwEAyMgBBwkaBwLQ0dLT0AcVCgZQ2sMYxsnfyggZAuDl5QI2Ccfm4OgX5Ozs
        ///7i7w8d/zFPX29y8H++XNKsALQFBZQQAE1+HzkMBcwoTgAliAR+ZYloYHsjBAtrCDPmX+gh6sSxZw
        ///AjwGWQQEyNIAQIIs/gB05D [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d12 {
            get {
                return ResourceManager.GetString("d12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAMEGBsRDPsdTTsVkXNR1cseHfciVicmmmcm0puSVleuwsMrGt8vcy/PQ0P79
        ////QAAACH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827/2AojiRTCGiqrmhRvowAzHRtzwJcyndP
        ///57oRz9cDBkNDQGBJWwZqxuMn6agmZlUHVIqsZR3P7JY79WYbAPGPXKZ9HQQ1ju2hVhvvMX1jdwzy
        ///a3t8ZloKX3qCGH1YcgBRiRaLAHFViJAVSUSWlxOZmnOckZ83j1wLCAiKozalEqepIgWkBQsUBwW4
        ///ubq7uAcVsqy0HQZPRL46xJrHGAvFny4lzavQF55EAzurM9gWwNoAsCHe2uESCE1MSs5OoCDnN07s
        ///lgRuVWEOCpN3NOUd9DdvtNgo5wyPnwD7DMEJ9MEZoUbtFtSglOBPJYPrQEjskUVAuhr+ASa8m4EQ
        ///X4KO+5q483GmARobIc3ZwO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d13 {
            get {
                return ResourceManager.GetString("d13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAANoAyR7JDqIOk+UT2mkaXWqdX6wfo65jpvCm6fIp7LOsrjSuMvcy9bm1v39
        ////QAAACH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827VEnijeS2FEEArMFgLGU8Loa63neAyHy2
        ///CLggrtArUgbC5GpgLBqUUFEzlggKrrcr8Maclgq4gGOMAIjHtpXU69myxmPB2ZEGdNmcRX3uYMzr
        ///AngdVWFwYwVwe4IchDlwDYZ0YYsbCkFzA5GKlBp7iQmGdXecF55ofHUGpBkHhWgAiK83a6sWblBB
        ///o7UVZbiXMLsYBL44O6QgtBY1vgEHlCcpOS7AFQl1QQTUbDTXYcYVCwgFWlcD2gwGA+rr7O3qqhY/
        ///xLA9SPNcF/bzuiP69/xP7qmR4W9ftSxYAFxREUDLEoJCyCXERwHMCjhAxlgyMIbBrBj+BfnIekjB
        ///DYMxBASMaQAAlIOAdkBeii [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d14 {
            get {
                return ResourceManager.GetString("d14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAARoBDqIOmOgY8EFBcRDPslaVceIfY65jq3LrdGonsrCtMvJusvcy9jo2PPQ
        ///0P39/SH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046807W0qiLF5paotBDCxLGOQpe+na3mwy79li
        ///40ADb0gpAI+sAnFoQDoVy5kCR6i2qr+BMnpq3h7gBAv8wOm4peyA/FiRcVs0ZwFkOwjvG0HemeLY
        ///DwZ5V3wcYn9gDoBAMYUYfl9gBYs4jih1YAMJbFSWGmp5nDdCnhiHLXmCmTdQpRhqTi1xrhansVeN
        ///tBZGty1nlgjBGl63pBjBCDMCAQDNzQEHyRYKsLKtFsvOz9EdB8za2tAXCwkqWAQF1xXe4OEHGgjf
        ///7eACQ/Hz7fUYAvjz+sr98l04EHCetBMEC4I7KAGBswAQn0UEAPFbABkO21WsCO4iBX7+zcgwA+Pw
        ///ABgGzhh2ABkO0AN5zRjKYw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d15 {
            get {
                return ResourceManager.GetString("d15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAAVpBTmIOWKfYsEGBcRDPslaVceIfY65jpzDnK3LrdaoocrGt8vcy9Pk0/PQ
        ///0P79/SH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827TKAnjpwQACgaHAnpjseZzkCAvHiWyHQv
        ///5ECKoEdE/YK5Q3HZQroStIA0JeXVnK4h9cFF1LgP6w0rsgbA4TPXTPYsomiGOjwLtDvQOvohALPv
        ///G3lbXA17VgCAgXBcfWiHiRuLYQiOdZAaZn4AlSkHlxlKg3SNdClNnxeHS1SoGV6rUaetFlqwKGOz
        ///GKGwnhkLCgutO0sCshQGA8nKBAbBGQYF0dLT1NEGFQgmVQHFGAYEyuHKChkF4ufnBTgL4Oji1xfm
        ///7u7qL/Lz4fUV9/j5L8j9xDmjII+AwWQG2yVMpk/EAnQJF/rblwwMOC4KBhjg4oChC4D+4vY8OEeO
        ///YDIHXAoQ4DhAAReADT20C7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d16 {
            get {
                return ResourceManager.GetString("d16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAANnAzqIOl6dXsEHB8RDPsxiXseGe4u4i5W9lazLrM6pnsrGt8vcy9jo2PPQ
        ///0P39/SH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827XMrijSRnDGhKGGLpjmcqp8prZwsx76hx
        ////5QCb1gA/mJDXstYWswIUFVUxXQhUY+sApud1aojnSyb1ZGfYI9zRn44BmcZId3ZstuGOJW+sY+z
        ///Dm0PO3wba38PBYKEhRo7ZwptaI0ZYilxkjI+lBh+XIMDeV0yS5wWlkmTpheeqSgEpasVQq40nAm4
        ///GldJm3wHAQDBwQEHCayoMwWxVb/CzsMInQZQ1MoVBwLZ2tvc2QcXCcDP4wACNwLk6cHmFujqz+wu
        ///7u/wFgf048by+PUUCcIBAg4TCCCguAAv5gE0SFBYPAnzyADL8u9AFgbC9JFQWFDQA3H+6yqAZJBF
        ///QIAsDQAkyHJv2D5nJwWBLE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d2 {
            get {
                return ResourceManager.GetString("d2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAANoAzmIOV2cXcEHB8RDPsxkX8eGe4+5j5zCnK3LrdKpoMrGt8vcy9Pk0/PQ
        ///0P79/SH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827TKAnjtwRACgaHAnpjmYqq8hrZ8k574Bw
        ////xQBb+gD3g7DZMvoSswC0BRUp2K6hNKHFgEIaB9UQM0qCnu/ULQsQPYsnt8H4wxetzvOdfxxUEvv
        ///HHlZWg17YQCAG4IqXwKGdokacFoBCHFmkRpmapcyB5kZSIN1fZQyS6AXh0kpRakXXKxPqK8WWLIo
        ///Y5ELCgsaorKfGby+LgYDyMkEBsUVOUkCtBTHycjLzRrU1dsKGAgCU1DRGNrbyd3DBObrBj8L6uvb
        ///7RgF8esFN/X22/gW5fvJsIn4B3CAwAXKCMBTmHChC4TmFEqEp6yCti/qtCgYYECLg3P+JAgO2PPA
        ///HDoJFB1oKUDA4wAFWrQRIE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d3 {
            get {
                return ResourceManager.GetString("d3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAMEGBsRDPsdTTsVkXNR1cseHfciVicmmmcm0puSVleuwsMrGt8vcy/PQ0P79
        ////QAAACH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827XAjijSRXAGgqFEvpkkaQzunx3tki0zxQ
        ///4ECKoEccBIEnIlF0dCFogWgqukMJmi4CzcFNoLgOGhPrqX7BMjDtSu4seGBHA6CeBdqd5zZOqE/x
        ///HHozYA1xYTSAG297DgOGPIkbcFwACnFrkRpmdJScnSk/mRgGjCh9nyhjohabSiqrGQeuPAEtsBgD
        ///szOqtxakugYaILyJCK0pA7YWSTMryhcFAtLT1NXSoRMIBFRRyaPHNRlDus03OuTYFePkVjfrukYW
        ///7+RsJczsxONUKFL8/fUjBNnhtgmghHFoOCkAcGoOAIMdtEy6JEYdikKNAnCZY8mBRIj+HI4ZOlRO
        ///iKkujihh3AFSGBEwAvrZsQ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d4 {
            get {
                return ResourceManager.GetString("d4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAARoBDqIOmOgY8EFBcRDPslaVceIfYm3iZW9la3LrdGonsrGt8vcy9jo2PPQ
        ///0P39/SH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827/2AojiRjFGiqrqhRvkwxzHRtzwVcyndP
        ///57oRz9cDBkPDAWFJWxJqxuMn+agqZtUHVIqsZR/P7JY79WYdBPGPXKZ9HwY1ju2hVh3vMX1jfxTy
        ///a3t8ZloKX3qCGH1YcgNRiRaLA3FViJAVSUSWlxOZmnOckZ83j1wJp4qjNqUSpwkjAgEAs7MBB68T
        ///Cga7vL2+uwoVsbS1tx0HssTEAQhByMrLzRkJydDKAi/U1tDYGALb1t2w4NwXB+TWuCHn6MrqrbQB
        ///8rXzAPLJASIJ1vf3yvkUvs3KIqvKvgNVGNB610HgsjcPqs16V41BlVhVGgBIUIWdvRD+EmtBDAmQ
        ///wQJiCB8gEJAFQIMq1Up2OA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d5 {
            get {
                return ResourceManager.GetString("d5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAAVpBTmIOWKfYsEGBcRDPslaVceIfY65jpzDnK3LrdaoocrGt8vcy9Pk0/PQ
        ///0P79/SH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827TKAnjpwQACgaHAnpjseZzkCAvHiWyHQv
        ///5ECKoEdE/YK5Q3HZQroStIA0JeXVnK4h9cFF1LgP6w0rsgbA4TPXTPYsomiGOjwLtDvQOvohALPv
        ///G3lbXA17VgCAgXBcfWiHiRuLYQiOdZAaZn4AlSkHlxlKg3SNdClNnxeHS1SoGV6rUaetFlqwKGOQ
        ///CwoLGqGwnokGA8PEBAa8FjtLArJkBgTE0cQKGAgmVQHMFQYF3d7f4N0GFwvQ0ucD4zgF6O3DBRfs
        ///7tLwL/Lz9BbC+NLIJPf83lVYUIyAOYMHDQp0AXAYQoT5KOwbAAYaFwXpuDiYxvDcngf+ESeYG+CA
        ///SwECGgco4DKx3oiGFPeEZE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d6 {
            get {
                return ResourceManager.GetString("d6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAMEGBsRDPsdTTsVkXNR1cseHfciVicmmmcm0puSVleuwsMrGt8vcy/PQ0P79
        ////QAAACH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827XAjijSRXAGgqFEvpkkaQzunx3tki0zxQ
        ///4ECKoEccBIEnIlF0dCFogWgqukMJmi4CzcFNoLgOGhPrqX7BMjDtSu4seGBHA6CeBdqd5zZOqE/x
        ///HHozYA1xYTSAG297DgOGPIkbcFwACnFrkRpmdJScnSk/mRgGjCh9nyhjohabSiqrGQeuPAEtsBgD
        ///szOqgCC8FaS6Bhq+L0kzK7YVCK0pA8oVxyosHTGuNhcIBFRRz6PNNcTgNKE3Oro+GUPoAEY36+ju
        ///0ewpvx3S6LyCVChS/f5sSAiyw21TQAlazjhI40ABgFNzUpVIyMhPPQpVCjUKwGWOJQf+FA92aGbo
        ///ELIJi0x1cURJY5U7I1IyEu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d7 {
            get {
                return ResourceManager.GetString("d7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAANoAyR7JDqIOk+UT2mkaXWqdX6wfo65jpvCm6fIp7LOsrjSuMvcy9bm1v39
        ////QAAACH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827VEnijeS2FEEArMFgLGU8Loa63neAyHy2
        ///CLggrtArUgbC5GpgLBqUUFEzlggKrrcr8Maclgq4gGOMAIjHtpXU69myxmPB2ZEGdNmcRX3uYMzr
        ///AngdVWFwYwVwe4IchDlwDYZ0YYsbCkFzA5GKlBp7iQmGdXecF55ofHUGpBkHhWgAiK83a6sWblBB
        ///o7UVZbiXMLsYBL44O8EZNb4BBxogtJwJdUEEwBUnKTku1RcGA97f4OHeqhMLCAVaVwPb5clKOhlI
        ///xDi6M7dQRBfy80s8+8T1GPybF5DDE35qLMjTsuKKigAM7VBJkg4LPYUr4AAZY8nAGAb+/b4I4SNr
        ///VgV5DMYQEDCmAQBQDg4W1H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d8 {
            get {
                return ResourceManager.GetString("d8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhPwA/ALMAAANoAzmIOV2cXcEHB8RDPsxkX8eGe4+5j5zCnK3LrdKpoMrGt8vcy9Pk0/PQ
        ///0P79/SH5BAEAAAwALAAAAAA/AD8AAAT+kMlJq7046827/2AojiRzCGiqruhRvowAzHRtzwJcyndP
        ///57oRz9cDBkNDQGBJWwZqxuNnGHhYEUrr44mTIpvabdXKBUS9HGqYMd7+0FNw+KAtn+EZtbURdnfx
        ///aXIPAn12gIEzbQEIYYaHGnpujW+PeYJPdGSUlRdJRFCcGJ6ff6EVo6R3UgsKC6KkN6oMrK4iBgO4
        ///uQQGtRIIB8DBwsPACBW3ubi7vRrIyc8KQc7PudEZCwTU2gYv2NrU3BgF39oFJePkz+YW0+m5zB/t
        ///7gPwC7oE2QP49/kEIvbU8AnMp+tYLi3ZrCgYYMCKg2oh5A3o84CaNQkEHVgpQMDhAAX+Vpz5A0Ew
        ///GcWAEwDiavhAQQEtAzQ+ID [rest of string was truncated]&quot;;.
        /// </summary>
        public static string d9 {
            get {
                return ResourceManager.GetString("d9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhDQALAOMAAAAAAL8AAAC/AL+/AAAAv78AvwC/v8DAwICAgP8AAP///////////////////////yH5BAEAAA8ALAAAAAANAAsAAAQd8L1E5ayS6ru5/kkGguLYeaRlYupovenbhrJMvxEAOw==.
        /// </summary>
        public static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;result&quot; style=&quot;page-break-after:always; clear: both; margin-bottom: 15px;&quot;&gt;
        ///    	&lt;tr&gt;
        ///        	&lt;th colspan=&quot;4&quot;&gt;Opponents&lt;/th&gt;
        ///            &lt;th&gt;Deal&lt;/th&gt;&lt;th&gt;Line&lt;/th&gt;
        ///            &lt;th&gt;Contract&lt;/th&gt;
        ///            &lt;th&gt;By&lt;/th&gt;
        ///            &lt;th&gt;Lead&lt;/th&gt;
        ///            &lt;th&gt;Tricks&lt;/th&gt;
        ///            &lt;th&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Result&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/th&gt;
        ///            &lt;th&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;Points&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/th&gt;
        ///        &lt;/tr&gt;.
        /// </summary>
        public static string histHead {
            get {
                return ResourceManager.GetString("histHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhSABIAOYAAO/v7z8/Py8vL21ucV9fX+0cJJ+fn8/Pz/NvId/f34+Pj09PTw8PD29vb6+vrx8fHyAgIICAgPDw8DAwMEBAQMDAwGBgYFBQUNDQ0ODg4KCgoLa2uLCwsJCQkHBwcP728fWKSpGSlMjIyfrJq/vU1e4qMfX19veldOPj5KOkpoiJi9ra2+84P/3w8frGyPzi4/aNkfBGTZqbnfiugvR/g/NxdnZ3eb+/wOzs7X+AgvaTWPm3kPiprNHR0vFUWvacZvJiaPm4uv3t4/zk1X9/f7+/vwAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhDQALAIABAAAAv////yH5BAEAAAEALAAAAAANAAsAAAIcjB+gC5jMkHpmnTlfxk1zSkHgZpHXB1ZN5rRGAQA7.
        /// </summary>
        public static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap printer3 {
            get {
                object obj = ResourceManager.GetObject("printer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Result&lt;/title&gt;&lt;/head&gt;&lt;style&gt;
        ///body {font: 12px Arial, Helvetica, sans-serif;}
        ///table {border-collapse: collapse; page-break-inside: avoid; page-break-after:always}
        ///.main td {padding: 0 10px;border: 0;margin: 0; vertical-align: text-top}
        ///table img {top: 1px;pos [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProtocolsHTMLBegin {
            get {
                return ResourceManager.GetString("ProtocolsHTMLBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string ProtocolsHTMLEnd {
            get {
                return ResourceManager.GetString("ProtocolsHTMLEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;{0}&quot; style=&quot;margin: 0 20px 10px 0;width:72px;height:72px; float:left&quot; /&gt;
        ///{1}&lt;h1 style=&quot;text-align:left; white-space: nowrap&quot;&gt;{2}&lt;/h1&gt;.
        /// </summary>
        public static string ProtocolsHTMLHeader {
            get {
                return ResourceManager.GetString("ProtocolsHTMLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td colspan=&quot;10&quot; rowspan=&quot;2&quot;&gt;&lt;/td&gt;&lt;td&gt;+/&amp;minus;&lt;/td&gt;&lt;td class=&quot;right&quot;&gt;{0}&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Total:&lt;/td&gt;&lt;td class=&quot;right&quot;&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string ProtocolsHTMLTableHistoryFooter {
            get {
                return ResourceManager.GetString("ProtocolsHTMLTableHistoryFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;float: left;&quot;&gt;History of pair # {0}&amp;nbsp;&lt;/span&gt;&lt;div style=&quot;float: left; width: 350px&quot;&gt;  {1} &lt;/div&gt;&lt;span style=&quot;float: left;&quot;&gt;{2:0.0}&amp;nbsp; &amp;nbsp;{3}&lt;/span&gt;.
        /// </summary>
        public static string ProtocolsHTMLTableHistoryHeader {
            get {
                return ResourceManager.GetString("ProtocolsHTMLTableHistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;hand&quot; style=&quot;text-align: left&quot;&gt;
        ///&lt;tr&gt;&lt;td valign=top&gt;&lt;h4&gt;{0}&lt;br&gt;{1}&lt;/h4&gt;&lt;/td&gt;{2}&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;{3}&lt;td valign=&quot;middle&quot; align=&quot;center&quot;&gt;{4}&lt;/td&gt;{5}&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td&gt;&amp;nbsp;&lt;/td&gt;{6}&lt;td&gt;&amp;nbsp;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td colspan=&quot;3&quot;&gt;
        ///&lt;br/&gt;
        ///&lt;table border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///&lt;tr&gt;&lt;td colspan=&quot;13&quot;&gt;&lt;small&gt;Maximum number of tricks:&lt;/small&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td class=&quot;an2&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;td class=&quot;an3&quot;&gt;{7}&lt;/td&gt;&lt;td class=&quot;an3&quot;&gt;{8}&lt;/td&gt;&lt;td class=&quot;an3&quot;&gt;{9}&lt;/td&gt;&lt;td class=&quot;an3&quot;&gt;{10}&lt;/td&gt;&lt;td cla [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProtocolsHTMLTablePBN {
            get {
                return ResourceManager.GetString("ProtocolsHTMLTablePBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;result&quot; style=&quot;page-break-after: auto&quot;&gt;&lt;tr&gt;
        ///&lt;th&gt;NS&lt;/th&gt;
        ///&lt;th&gt;EW&lt;/th&gt;
        ///&lt;th&gt;Contract&lt;/th&gt;
        ///&lt;th&gt;By&lt;/th&gt;
        ///&lt;th&gt;Lead&lt;/th&gt;
        ///&lt;th&gt;Tricks&lt;/th&gt;
        ///&lt;th&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;Result&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/th&gt;
        ///&lt;th&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;NS&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/th&gt;
        ///&lt;th&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;EW&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;/th&gt;&lt;/tr&gt;.
        /// </summary>
        public static string ProtocolsHTMLTableProtocolHeader {
            get {
                return ResourceManager.GetString("ProtocolsHTMLTableProtocolHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td class=&quot;right&quot;&gt;{0}&lt;/td&gt;&lt;td class=&quot;right&quot;&gt;{1}&lt;/td&gt;{2}&lt;td class=&quot;right&quot;&gt;{3}&lt;/td&gt;&lt;td class=&quot;right&quot;&gt;{4}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string ProtocolsHTMLTableProtocolRow {
            get {
                return ResourceManager.GetString("ProtocolsHTMLTableProtocolRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td class=&quot;right&quot;&gt;{0}&lt;/td&gt;
        ///&lt;td class=&quot;right&quot;&gt;{1}&lt;/td&gt;
        ///&lt;td&gt;{2}&lt;/td&gt;
        ///&lt;td class=&quot;right&quot;&gt;{3:0.0}&lt;/td&gt;
        ///&lt;td&gt;{4}&lt;/td&gt;
        ///&lt;td class=&quot;right&quot;&gt;{5}&lt;/td&gt;
        ///&lt;td class=&quot;right&quot;&gt;{6}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string ProtocolsHTMLTableResultBody {
            get {
                return ResourceManager.GetString("ProtocolsHTMLTableResultBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;.
        /// </summary>
        public static string ProtocolsHTMLTableResultFooter {
            get {
                return ResourceManager.GetString("ProtocolsHTMLTableResultFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;result&quot; style=&quot;width: 100%; font-size: 16px;clear: both;&quot;&gt;
        ///&lt;tr&gt;&lt;th&gt;Pos&lt;/th&gt;
        ///&lt;th&gt;#&lt;/th&gt;
        ///&lt;th&gt;Names&lt;/th&gt;
        ///&lt;th&gt;WK&lt;/th&gt;
        ///&lt;th&gt;Reg&lt;/th&gt;
        ///&lt;th&gt; +/&amp;minus;&lt;/th&gt;
        ///&lt;th&gt;Result&lt;/th&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        public static string ProtocolsHTMLTableResultHeader {
            get {
                return ResourceManager.GetString("ProtocolsHTMLTableResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 style=&quot;text-align: left; margin: 0; paddin: 0&quot;&gt;{0}&lt;/h1&gt;.
        /// </summary>
        public static string ProtocolsHTMLTitle {
            get {
                return ResourceManager.GetString("ProtocolsHTMLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/gif;base64,R0lGODlhDQALAIAAAAAAAP///yH5BAEAAAEALAAAAAANAAsAAAIYjA+nCr3c3It00YsuDnr3akgJN1rSpB0FADs=.
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap window_split_hor {
            get {
                object obj = ResourceManager.GetObject("window_split_hor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Write {
            get {
                object obj = ResourceManager.GetObject("Write", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
