//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMtoKoPSTests.Integration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClubResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClubResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMtoKoPSTests.Integration.ClubResources", typeof(ClubResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11 *BAZA
        ///11 *RUND
        ///3 *ROZD. W RUNDZIE
        ///0 *SEKTORY MITCHELLA
        ///11 *SKOK NUMERACJI
        ///11 *RUND DO OBROTU
        ///0 *POWIELANIE
        ///14 *ZAWODNICY
        ///7 *ZAPISY
        ///6 *SREDNIA, &lt;0 = PESZKOWKA
        ///12 *MAX
        ///0 *BAZA / 2
        ///22 *2*BAZA
        ///33 *ROZDANIA
        ///7 *STOLIKI W SEKTORZE NIETYPOWYM
        ///2 *1   NUMERY NA SALI
        ///9 *2
        ///8 *3
        ///3 *4
        ///14 *5
        ///4 *6
        ///7 *7
        ///13 *8
        ///5 *9
        ///6 *10
        ///11 *11
        ///12 *12
        ///10 *13
        ///1 *14
        ///7 *LICZBA ZAP. DLA KOMPLETU #1
        ///0 *W SEKTORZE NIETYPOWYM
        ///14      1 *NS
        ///1      1 *EW
        ///2      2 *NS
        ///10      2 *EW
        ///6      3 *NS
        ///12      3 *EW
        ///9   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _INF {
            get {
                return ResourceManager.GetString("_INF", resourceCulture);
            }
        }
        
        internal static byte[] _KNT {
            get {
                object obj = ResourceManager.GetObject("_KNT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _LUC {
            get {
                object obj = ResourceManager.GetObject("_LUC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _NAG {
            get {
                object obj = ResourceManager.GetObject("_NAG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _SES {
            get {
                object obj = ResourceManager.GetObject("_SES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _ZAP {
            get {
                object obj = ResourceManager.GetObject("_ZAP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Result&lt;/title&gt;&lt;/head&gt;&lt;style&gt;
        ///body {font: 12px Arial, Helvetica, sans-serif;}
        ///table {border-collapse: collapse; page-break-inside: avoid; page-break-after:always}
        ///.main td {padding: 0 10px;border: 0;margin: 0; vertical-align: text-top}
        ///table img {top: 1px;pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrintAllHistories {
            get {
                return ResourceManager.GetString("PrintAllHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Result&lt;/title&gt;&lt;/head&gt;&lt;style&gt;
        ///body {font: 12px Arial, Helvetica, sans-serif;}
        ///table {border-collapse: collapse; page-break-inside: avoid; page-break-after:always}
        ///.main td {padding: 0 10px;border: 0;margin: 0; vertical-align: text-top}
        ///table img {top: 1px;pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrintListHistories {
            get {
                return ResourceManager.GetString("PrintListHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Result&lt;/title&gt;&lt;/head&gt;&lt;style&gt;
        ///body {font: 12px Arial, Helvetica, sans-serif;}
        ///table {border-collapse: collapse; page-break-inside: avoid; page-break-after:always}
        ///.main td {padding: 0 10px;border: 0;margin: 0; vertical-align: text-top}
        ///table img {top: 1px;pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrintProtocols {
            get {
                return ResourceManager.GetString("PrintProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Result&lt;/title&gt;&lt;/head&gt;&lt;style&gt;
        ///body {font: 12px Arial, Helvetica, sans-serif;}
        ///table {border-collapse: collapse; page-break-inside: avoid; page-break-after:always}
        ///.main td {padding: 0 10px;border: 0;margin: 0; vertical-align: text-top}
        ///table img {top: 1px;pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrintResults {
            get {
                return ResourceManager.GetString("PrintResults", resourceCulture);
            }
        }
    }
}
