//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMtoKoPSTests.Integration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MultySectionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultySectionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMtoKoPSTests.Integration.MultySectionResources", typeof(MultySectionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 *BAZA
        ///7 *RUND
        ///2 *ROZD. W RUNDZIE
        ///4 *SEKTORY MITCHELLA
        ///10 *SKOK NUMERACJI
        ///7 *RUND DO OBROTU
        ///0 *POWIELANIE
        ///56 *ZAWODNICY
        ///28 *ZAPISY
        ///27 *SREDNIA, &lt;0 = PESZKOWKA
        ///54 *MAX
        ///0 *BAZA / 2
        ///14 *2*BAZA
        ///14 *ROZDANIA
        ///0 *STOLIKI W SEKTORZE NIETYPOWYM
        ///31 *1   NUMERY NA SALI
        ///32 *2
        ///33 *3
        ///34 *4
        ///35 *5
        ///36 *6
        ///37 *7
        ///51 *8
        ///52 *9
        ///53 *10
        ///54 *11
        ///55 *12
        ///56 *13
        ///57 *14
        ///11 *15
        ///12 *16
        ///13 *17
        ///14 *18
        ///15 *19
        ///16 *20
        ///17 *21
        ///21 *22
        ///22 *23
        ///23 *24
        ///24 *25
        ///25 *26
        ///26 *27
        ///27 *28
        ///1 *29
        ///2 *30
        ///3 *31
        ///4 *32
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _INF {
            get {
                return ResourceManager.GetString("_INF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _INR {
            get {
                object obj = ResourceManager.GetObject("_INR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _KNT {
            get {
                object obj = ResourceManager.GetObject("_KNT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _LUC {
            get {
                object obj = ResourceManager.GetObject("_LUC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _NAG {
            get {
                object obj = ResourceManager.GetObject("_NAG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _PBN {
            get {
                object obj = ResourceManager.GetObject("_PBN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _SES {
            get {
                object obj = ResourceManager.GetObject("_SES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _ZAP {
            get {
                object obj = ResourceManager.GetObject("_ZAP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Result&lt;/title&gt;&lt;/head&gt;&lt;style&gt;
        ///body {font: 12px Arial, Helvetica, sans-serif;}
        ///table {border-collapse: collapse; page-break-inside: avoid; page-break-after:always}
        ///.main td {padding: 0 10px;border: 0;margin: 0; vertical-align: text-top}
        ///table img {top: 1px;pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrintAllHistories {
            get {
                return ResourceManager.GetString("PrintAllHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Result&lt;/title&gt;&lt;/head&gt;&lt;style&gt;
        ///body {font: 12px Arial, Helvetica, sans-serif;}
        ///table {border-collapse: collapse; page-break-inside: avoid; page-break-after:always}
        ///.main td {padding: 0 10px;border: 0;margin: 0; vertical-align: text-top}
        ///table img {top: 1px;pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrintListHistories {
            get {
                return ResourceManager.GetString("PrintListHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Result&lt;/title&gt;&lt;/head&gt;&lt;style&gt;
        ///body {font: 12px Arial, Helvetica, sans-serif;}
        ///table {border-collapse: collapse; page-break-inside: avoid; page-break-after:always}
        ///.main td {padding: 0 10px;border: 0;margin: 0; vertical-align: text-top}
        ///table img {top: 1px;pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrintProtocols {
            get {
                return ResourceManager.GetString("PrintProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;Result&lt;/title&gt;&lt;/head&gt;&lt;style&gt;
        ///body {font: 12px Arial, Helvetica, sans-serif;}
        ///table {border-collapse: collapse; page-break-inside: avoid; page-break-after:always}
        ///.main td {padding: 0 10px;border: 0;margin: 0; vertical-align: text-top}
        ///table img {top: 1px;pos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrintResults {
            get {
                return ResourceManager.GetString("PrintResults", resourceCulture);
            }
        }
    }
}
